name: Deploy Spacire Campaign Tool
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Replace environment variables
        run: |
          sed -i "s/{{SPACIRE_GIST_ID}}/${{ secrets.SPACIRE_GIST_ID }}/g" index.html
          sed -i "s/{{SPACIRE_GITHUB_TOKEN}}/${{ secrets.SPACIRE_GITHUB_TOKEN }}/g" index.html
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
